export const photographers = [
  {
    id: "p1",
    name: "Omar Al-Khatib",
    specialty: "Product & E-commerce",
    location: "Doha",
    rating: 4.8,
    priceQAR: 450,
    verified: true,
    bio: "Minimal, clean product photography for brands, restaurants, and online stores. Fast turnaround and consistent lighting.",
    reviews: [
      { author: "Sara", stars: 5, text: "Great direction and very professional results." },
      { author: "Fahad", stars: 4.7, text: "On time and the photos looked premium." },
      { author: "Nora", stars: 4.8, text: "Smooth communication, excellent edits." },
    ],
  },
  {
    id: "p2",
    name: "Lina Haddad",
    specialty: "Portrait & Lifestyle",
    location: "Doha",
    rating: 4.6,
    priceQAR: 380,
    verified: false,
    bio: "Natural light portraits and lifestyle shoots with a calm, minimal aesthetic.",
    reviews: [
      { author: "Aisha", stars: 4.6, text: "Loved the vibe and the composition." },
      { author: "Mariam", stars: 4.5, text: "Very friendly and creative." },
      { author: "Khaled", stars: 4.7, text: "Clean edits and great poses." },
    ],
  },
  {
    id: "p3",
    name: "Hassan Noor",
    specialty: "Wedding & Events",
    location: "Lusail",
    rating: 4.9,
    priceQAR: 750,
    verified: true,
    bio: "Elegant weddings and events. Storytelling, details, and timeless color grading.",
    reviews: [
      { author: "Rana", stars: 5, text: "Captured every important moment." },
      { author: "Yousef", stars: 4.9, text: "High-end look, exactly what we wanted." },
      { author: "Dana", stars: 4.8, text: "Super organized and professional." },
    ],
  },
];

export const models = [
  {
    id: "m1",
    name: "Haya",
    category: "Commercial",
    location: "Doha",
    rating: 4.7,
    priceQAR: 300,
    verified: true,
    heightCm: 170,
    languages: ["AR", "EN"],
    bio: "Commercial shoots for beauty, lifestyle and e-commerce. Calm presence, minimal posing style.",
  },
  {
    id: "m2",
    name: "Mona",
    category: "Fashion",
    location: "Doha",
    rating: 4.8,
    priceQAR: 450,
    verified: true,
    heightCm: 175,
    languages: ["AR", "EN"],
    bio: "Fashion editorial and brand campaigns. Strong runway posture and clean silhouettes.",
  },
  {
    id: "m3",
    name: "Yara",
    category: "Beauty",
    location: "Lusail",
    rating: 4.6,
    priceQAR: 350,
    verified: false,
    heightCm: 168,
    languages: ["AR", "EN"],
    bio: "Beauty and skincare product shoots. Clean, minimal looks and close-up experience.",
  },
];
